build:
	cargo build
build-release:
	cargo build --release

triangle: build-release
	#!/usr/bin/env bash
	n=100000
	for ((i = 0; i <= n; i+=1000)); do
	  for ((j = 0; j <= n- i; j+=1000)); do
	    if [[ $((i + j)) -le $n ]]; then
	      k=$((n - i - j))
	      ./target/release/simulation_runner -n $n -j 3 -k 3 --initial-config $i,$j,$k --batch-size 20 --model gossip --output triangle > /dev/null 2> /dev/null
	    fi
	  done
	done
render-triangle:
	cargo run --release --bin export -- -i output/triangle/simulation.json triangle --generate-latex

k-plot: build-release
	./target/release/simulation_runner --total-k 25 --total-j 12 --model gossip --output k-plot
render-k-plot:
	cargo run --release --bin export -- -i output/k-plot/simulation.json k --generate-latex

n-plot: build-release
	./target/release/simulation_runner --n 10000 --n-step-size 10000 --total-n 100000 --total-j 12 --batch-size 50 --model population --output n-plot
render-n-plot:
	cargo run --release --bin export -- -i output/n-plot/simulation.json n --generate-latex

entropy-plot: build-release
	./target/release/simulation_runner --total-j 12 --batch-size 50 --model gossip --output entropy-plot
render-entropy-plot:
	cargo run --release --bin export -- -i output/entropy-plot/simulation.json entropy --generate-latex
